import axios from "axios";
import * as dotenv from "dotenv";
import * as path from "path";
import * as fs from "fs";
import { google } from "googleapis";
import { promisify } from "util";
import { pipeline } from "stream";

dotenv.config();

const streamPipeline = promisify(pipeline);

const VEO_API_KEY = process.env.VEO_API_KEY;
const YOUTUBE_CLIENT_ID = process.env.YOUTUBE_CLIENT_ID;
const YOUTUBE_CLIENT_SECRET = process.env.YOUTUBE_CLIENT_SECRET;
const YOUTUBE_REDIRECT_URI = process.env.YOUTUBE_REDIRECT_URI;
const YOUTUBE_REFRESH_TOKEN = process.env.YOUTUBE_REFRESH_TOKEN;

async function downloadVideo(videoUrl: string, filename: string): Promise<string> {
    const uploadDir = path.join(process.cwd(), "uploads", "videos");
    if (!fs.existsSync(uploadDir)) {
        fs.mkdirSync(uploadDir, { recursive: true });
    }
    const localPath = path.join(uploadDir, filename);
    const downloadUrl = `${videoUrl}${videoUrl.includes('?') ? '&' : '?'}key=${VEO_API_KEY}`;
    const response = await axios({
        method: "GET",
        url: downloadUrl,
        responseType: "stream",
    });
    await streamPipeline(response.data, fs.createWriteStream(localPath));
    console.log(`Video downloaded to: ${localPath}`);
    return localPath;
}

async function uploadToYouTube(videoPath: string, title: string, description: string) {
    console.log("Initializing YouTube API...");
    const oauth2Client = new google.auth.OAuth2(
        YOUTUBE_CLIENT_ID,
        YOUTUBE_CLIENT_SECRET,
        YOUTUBE_REDIRECT_URI
    );
    oauth2Client.setCredentials({ refresh_token: YOUTUBE_REFRESH_TOKEN });
    const youtube = google.youtube({ version: "v3", auth: oauth2Client });

    console.log(`Uploading ${videoPath} to YouTube...`);
    const res = await youtube.videos.insert({
        part: ["snippet", "status"],
        requestBody: {
            snippet: {
                title,
                description,
                categoryId: "22",
            },
            status: {
                privacyStatus: "public",
            },
        },
        media: {
            body: fs.createReadStream(videoPath),
        },
    });

    console.log(`Success! Video URL: https://www.youtube.com/watch?v=${res.data.id}`);
    return res.data.id;
}

async function run() {
    if (!VEO_API_KEY || !YOUTUBE_REFRESH_TOKEN) {
        console.error("Missing required environment variables (VEO_API_KEY or YOUTUBE_REFRESH_TOKEN)");
        return;
    }

    const prompt = "A futuristic neon forest with bioluminescent plants and robotic animals moving gracefully";
    const model = "veo-3.1-generate-preview";
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:predictLongRunning?key=${VEO_API_KEY}`;

    console.log(`Step 1: Generating Veo3 video for: "${prompt}"...`);
    try {
        const response = await axios.post(endpoint, {
            instances: [{ prompt }],
        });

        const operationName = response.data.name;
        console.log(`Operation started: ${operationName}`);

        let videoUrl: string | null = null;
        let done = false;
        while (!done) {
            await new Promise(r => setTimeout(r, 10000));
            const status = await axios.get(`https://generativelanguage.googleapis.com/v1beta/${operationName}?key=${VEO_API_KEY}`);
            if (status.data.done) {
                done = true;
                if (status.data.error) throw new Error(status.data.error.message);
                videoUrl = status.data.response?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri;
            } else {
                console.log("...processing...");
            }
        }

        if (!videoUrl) throw new Error("No video URL returned from Veo");
        console.log(`Step 2: Downloading video from ${videoUrl}...`);
        const localPath = await downloadVideo(videoUrl, `veo_${Date.now()}.mp4`);

        console.log("Step 3: Publishing to YouTube...");
        await uploadToYouTube(
            localPath,
            "Amazing AI Video - Veo 3.1",
            `Generated by Google Veo 3.1 AI.\nPrompt: ${prompt}\n#AI #Veo3 #GoogleAI`
        );

    } catch (error: any) {
        console.error("Error in process:", error.response?.data || error.message);
    }
}

run();
